### Config file with the hyperparameters for the models and trainings

###### MLP ######
ftops_Mlp:

  ## Architecture
  net_name: ftops_Mlp

  ## Input
  input_dim: 12 ## for j,b,e-,e+,mu-,mu+,g
  #input_dim: 9 ## for j,b,l,g
  num_features: 92
  aux_dim: 2

  ## Default hyperparameters for training
  training:
    optimizer_name: adam
    batch_size: 500
    n_epochs: 1000
    lr: 0.00001
    #scheduler: MultiStepLR
    scheduler: ReduceLROnPlateau
    lr_milestone: 50
    weight_decay: 0.000005
    rep_dim: 10
    
###### Transformer ######
ftops_Transformer:

  ## Architecture
  net_name: ftops_Transformer
  net_version: standard ## Options: standard, SMids, SMcoupling
  num_heads: 8
  num_layers: 8
  num_cls_layers: 2
  block_params: None
  cls_block_params: {'dropout': 0, 'attn_dropout': 0, 'activation_dropout': 0}
  fc_params: [[64, 0.], [256, 0.], [64, 0.]]
  aux_fc_params: [[32, 0.], [32, 0.]]
  embed_dims: [128, 512, 128]
  pair_embed_dims: [64, 64, 64] # None for no interactions
  activation: gelu
  add_bias_attn: False
  seq_len: -1
  trim: False
  for_inference: False
  use_amp: False

  ## Input
  input_dim: 12 ## for j,b,e-,e+,mu-,mu+,g
  #input_dim: 9 ## for j,b,l,g
  num_features: 18
  aux_dim: 2

  ## Default hyperparameters for training
  training:
    optimizer_name: adam
    batch_size: 500
    n_epochs: 500
    lr: 0.00001
    #scheduler: MultiStepLR
    scheduler: ReduceLROnPlateau
    lr_milestone: 50
    weight_decay: 0.000005
    rep_dim: 10

###### ParticeNet ######
ftops_ParticleNET:

  ## Architecture
  net_name: ftops_ParticleNET
  embed_dims: [128, 128, 128]
  pair_embed_dims: [64, 64, 64]
  fc_params: [[64, 0.], [256, 0.], [64, 0.]]
  knn: 2
  conv_params: [[32, 32, 32], [64, 64, 64]]
  aux_fc_params: []
  #attention_dims: [64, 64, 64]

  ## Input
  input_dim: 12 ## for j,b,e-,e+,mu-,mu+,g
  #input_dim: 9 ## for j,b,l,g
  num_features: 18
  aux_dim: 2

  ## Default hyperparameters for training
  training:
    optimizer_name: adam
    batch_size: 500
    n_epochs: 500
    lr: 0.00001
    scheduler: ReduceLROnPlateau
    lr_milestone: 50
    weight_decay: 0.000005
    rep_dim: 10
